### ISSUE TITLE
papers

### ISSUE THREAD

**Issue by liqiumei-bjtu** [yacine902/ILIBWM#1]
Hello author, I am studying indoor localization recently and I am very interested in the code you shared. Could I read your related papers further? If you feel offended, I'm sorry

**Comment by yacine902** [comment]
Hello @liqiumei-bjtu,
Thank you for your interest.
There are no papers associated with the code actually, it was part of a term project at a masters program.
Attached is the project report.
[Final Report.pdf](https://github.com/yacine902/ILIBWM/files/5212409/Final.Report.pdf)

**Comment by liqiumei-bjtu** [comment]
Thank you so much for your reply! Wish you all the best!
